nombre=input("ingrese su nombre:")
apellido=input("ingrse su apllido:")
cedula=input("ingrse su cedula:")
edad=int(input("ingrse su edad:"))
curso=input("ingrse su curso:")
print("nombre y apellido:",nombre,apellido)
print("cedula:",cedula)
print("edad:",edad)
print("curso:",curso)