-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 10:35:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `autorid` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechnacautor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`autorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `libroid` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `añopublicacion` VARCHAR(45) NULL,
  `autor_autorid` INT NOT NULL,
  PRIMARY KEY (`libroid`),
  INDEX `fk_libros_autor_idx` (`autor_autorid` ASC) ,
  CONSTRAINT `fk_libros_autor`
    FOREIGN KEY (`autor_autorid`)
    REFERENCES `mydb`.`autor` (`autorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `categoriaid` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `libros_libroid` INT NOT NULL,
  PRIMARY KEY (`categoriaid`),
  INDEX `fk_categoria_libros1_idx` (`libros_libroid` ASC) 
  ,
  CONSTRAINT `fk_categoria_libros1`
    FOREIGN KEY (`libros_libroid`)
    REFERENCES `mydb`.`libros` (`libroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historialprestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historialprestamo` (
  `historialprestamoid` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`historialprestamoid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo` (
  `prestamoid` INT NOT NULL,
  `fechaprestamo` VARCHAR(45) NULL,
  `devolver` VARCHAR(45) NULL,
  `libros_libroid` INT NOT NULL,
  `historialprestamo_historialprestamoid` INT NOT NULL,
  PRIMARY KEY (`prestamoid`),
  INDEX `fk_prestamo_libros1_idx` (`libros_libroid` ASC) 
  ,
  INDEX `fk_prestamo_historialprestamo1_idx` (`historialprestamo_historialprestamoid` ASC) ,
  CONSTRAINT `fk_prestamo_libros1`
    FOREIGN KEY (`libros_libroid`)
    REFERENCES `mydb`.`libros` (`libroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_historialprestamo1`
    FOREIGN KEY (`historialprestamo_historialprestamoid`)
    REFERENCES `mydb`.`historialprestamo` (`historialprestamoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`multas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`multas` (
  `multasid` INT NOT NULL,
  `monto` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `fechamulta` VARCHAR(45) NULL,
  `pagada` VARCHAR(45) NULL,
  PRIMARY KEY (`multasid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `reversaid` INT NOT NULL,
  `fechareserva` VARCHAR(45) NULL,
  `reservascol` VARCHAR(45) NULL,
  `libros_libroid` INT NOT NULL,
  PRIMARY KEY (`reversaid`, `libros_libroid`),
  INDEX `fk_reservas_libros1_idx` (`libros_libroid` ASC),
  CONSTRAINT `fk_reservas_libros1`
    FOREIGN KEY (`libros_libroid`)
    REFERENCES `mydb`.`libros` (`libroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuarioid` INT NOT NULL,
  `nombreusu` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `prestamo_prestamoid` INT NOT NULL,
  `multas_multasid` INT NOT NULL,
  `reservas_reversaid` INT NOT NULL,
  PRIMARY KEY (`usuarioid`),
  INDEX `fk_usuario_prestamo1_idx` (`prestamo_prestamoid` ASC),
  INDEX `fk_usuario_multas1_idx` (`multas_multasid` ASC),
  INDEX `fk_usuario_reservas1_idx` (`reservas_reversaid` ASC) ,
  CONSTRAINT `fk_usuario_prestamo1`
    FOREIGN KEY (`prestamo_prestamoid`)
    REFERENCES `mydb`.`prestamo` (`prestamoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_multas1`
    FOREIGN KEY (`multas_multasid`)
    REFERENCES `mydb`.`multas` (`multasid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_reservas1`
    FOREIGN KEY (`reservas_reversaid`)
    REFERENCES `mydb`.`reservas` (`reversaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`librosautores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`librosautores` (
  `libroautroesid` INT NOT NULL,
  PRIMARY KEY (`libroautroesid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`librosautores_has_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`librosautores_has_libros` (
  `librosautores_libroautroesid` INT NOT NULL,
  `libros_libroid` INT NOT NULL,
  PRIMARY KEY (`librosautores_libroautroesid`, `libros_libroid`),
  INDEX `fk_librosautores_has_libros_libros1_idx` (`libros_libroid` ASC) ,
  INDEX `fk_librosautores_has_libros_librosautores1_idx` (`librosautores_libroautroesid` ASC) ,
  CONSTRAINT `fk_librosautores_has_libros_librosautores1`
    FOREIGN KEY (`librosautores_libroautroesid`)
    REFERENCES `mydb`.`librosautores` (`libroautroesid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_librosautores_has_libros_libros1`
    FOREIGN KEY (`libros_libroid`)
    REFERENCES `mydb`.`libros` (`libroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
